# Generated by Django 3.1.5 on 2021-01-19 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название анкеты')),
                ('slug', models.SlugField(unique=True, verbose_name='уникальная ссылка для доступа')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('text', models.TextField(verbose_name='Текст документа для генерации в контейнере')),
                ('html_text', models.TextField(verbose_name='Текст документа для отображения на странице завершения html')),
            ],
        ),
        migrations.CreateModel(
            name='EndPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название страницы')),
                ('html_text', models.TextField(verbose_name='Текст страницы завершения в html')),
            ],
        ),
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название формы')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название письма')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('text', models.TextField(verbose_name='Текст письма в html')),
            ],
        ),
        migrations.CreateModel(
            name='FilledApplicationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(editable=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Емаил')),
                ('code', models.PositiveSmallIntegerField(default=7864)),
                ('signification', models.CharField(blank=True, max_length=255, null=True)),
                ('application_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_forms', to='main.applicationform', verbose_name='Анкета')),
            ],
        ),
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название поля')),
                ('slug', models.SlugField(unique=True, verbose_name='Название переменной')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main.formmodel', verbose_name='Форма')),
            ],
        ),
        migrations.AddField(
            model_name='applicationform',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.document', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='end_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.endpage', verbose_name='Страница завершения'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.formmodel', verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='Электронные сообщение'),
        ),
    ]
