# Generated by Django 3.1.5 on 2021-01-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filledapplicationform',
            name='code',
            field=models.PositiveSmallIntegerField(default=9647),
        ),
        migrations.AlterField(
            model_name='filledapplicationform',
            name='values',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
