# Generated by Django 3.1.5 on 2021-01-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210119_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filledapplicationform',
            name='code',
            field=models.PositiveSmallIntegerField(default=5097),
        ),
        migrations.AlterField(
            model_name='filledapplicationform',
            name='values',
            field=models.JSONField(null=True),
        ),
    ]
